checks:
    php:
        code_rating: true
        duplication: true
build:
    enviroment:
        php: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
filter:
    excluded_paths:
        - tests/*
